// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_api_2.Models;

#nullable disable

namespace web_api_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web_api_2.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("CategoryName")
                        .HasColumnOrder(1);

                    b.Property<int>("CategoryStatus")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("CategoryId");

                    b.ToTable("Category", "dbo", t =>
                        {
                            t.HasComment("ตารางไว้เก็บรายชื่อหมวดหมู่สินค้า");
                        });
                });

            modelBuilder.Entity("web_api_2.Models.Products", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(1);

                    b.Property<string>("ProductPicture")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnOrder(4);

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnOrder(2);

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "dbo", t =>
                        {
                            t.HasComment("ตารางไว้เก็บข้อมูลสินค้า");
                        });
                });

            modelBuilder.Entity("web_api_2.Models.Products", b =>
                {
                    b.HasOne("web_api_2.Models.Category", "CategoryInfo")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
